name: WebApp Docker Image

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ernestobv
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:
        docker build . --file WebApp.Dockerfile --tag ernestobv/oai-embeddings:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker tag ernestobv/oai-embeddings:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER ernestobv/oai-embeddings:latest;
        docker push ernestobv/oai-embeddings:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker push ernestobv/oai-embeddings:latest;
        
        docker build . --file BatchProcess.Dockerfile --tag ernestobv/oai-batch:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker tag ernestobv/oai-batch:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER ernestobv/oai-batch:latest;
        docker push ernestobv/oai-batch:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker push ernestobv/oai-batch:latest;
